[tool.poetry]
name = "almasim"
version = "2.1.2"
description = "An ALMA Simulation package for a more civilized era."
authors = ["Michele Delli Veneri <micheledelliveneri@gmail.com>"]
readme = "README.rst"
repository = "https://github.com/MicheleDelliVeneri/ALMASim"
homepage = "https://github.com/MicheleDelliVeneri/ALMASim"
documentation = "https://almasim.readthedocs.io/en/latest"

[tool.poetry.dependencies]
python = ">=3.12.4"
astropy = "*"
pyvo = "*"
numpy = "*"
pandas = "*"
matplotlib = "*"
seaborn = "*"
pyqt6 = "*"
tqdm = "*"
scipy = "*"
h5py = "*"
kaggle = "*"
dask = "*"
dask-expr = "*"
dask-jobqueue = "*"
distributed = "*"
astromartini = "*"
Hdecompose = "*"
paramiko = "*"
pysftp = "*"
tenacity = "*"
nifty8 = "*"
setuptools = "*"

[tool.poetry.group.dev.dependencies]  # Optional: Development dependencies
pytest = "*"
pytest-qt = "*"
flake8 = "*"
mypy = "*"
black = "*"